test

diff --git a/redis b/redis
--- a/redis
+++ b/redis
@@ -1,83 +1,133 @@
-#!/bin/sh
+#!/bin/bash
+#chkconfig: 2345 55 25
+#description: Starts,stops and restart the redis-server
+#Ver:1.1  
+#Write by ND chengh(200808)
+#usage: ./script_name -p [port] {start|stop|status|restart}
 
-### BEGIN INIT INFO
-# Provides:           redis
-# Required-Start:     $syslog
-# Required-Stop:      $syslog
-# Should-Start:       $all
-# Should-Stop:        $all
-# Default-Start:      2 3 4 5
-# Default-Stop:       0 1 6
-# X-Interactive:      true
-# Short-Description:  start and stop redis
-# Description:        persistent key-value db
-### END INIT INFO
+# Source function library.
+. /etc/rc.d/init.d/functions
 
-NAME=redis
-PATH=/opt/bin:/opt/sbin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-EXEC=/opt/sbin/redis-server
-CLIEXEC=/opt/sbin/redis-cli
-CONF=/etc/$NAME/$NAME.conf
-PIDFILE=/var/run/$NAME.pid
-SOCKET=/var/run/$NAME.sock
-PERF=/tmp/redis.sysctl
-KERNELPG=/sys/kernel/mm/transparent_hugepage/enabled
+# Source networking configuration.
+. /etc/sysconfig/network
 
-[ -x /opt/sbin/redis-server ] || exit 0
+# Check networking is up.
+[ "$NETWORKING" = "no" ] && exit 0
 
-set -e
+RETVAL=0
+REDIS_PORT=6379
+PID=
 
-# tune system for better redis performance
-if [ ! -f $PERF ]; then
-  echo "tunning redis..." &>> $PERF
-  echo never > $KERNELPG && cat $KERNELPG &>> $PERF
-  sysctl -w net.core.somaxconn=65535 &>> $PERF
-  sysctl -w vm.overcommit_memory=1 &>> $PERF
-  echo "tuned." &>> $PERF && cat $PERF
+if [ "$1" = "-p" ]; then
+    REDIS_PORT=$2
+    shift 2
 fi
 
-case $1 in
-  start)
-    if [ ! -f $PIDFILE ]; then
-      echo -n "Starting $NAME: "
-      start-stop-daemon --start --pidfile $PIDFILE --exec $EXEC -- $CONF
-      echo "waiting for redis db to start..."
-      while [ ! -f $PIDFILE ]; do
-        sleep 0.1;
-      done
-    fi
-    PID=$(cat $PIDFILE)
-    echo "running with pid: $PID"
-    ;;
-  stop)
-    if [ ! -f $PIDFILE ]; then
-      echo "redis is already stopped"
+REDIS_DIR="/usr/local/redis"
+REDIS="${REDIS_DIR}/bin/redis-server"
+PROG=$(basename $REDIS)
+
+CONF="${REDIS_DIR}/etc/redis-${REDIS_PORT}.conf"
+
+if [ ! -f $CONF ]; then
+   if [ -f "${REDIS_DIR}/etc/redis.conf" ];then
+      CONF="${REDIS_DIR}/etc/redis.conf"
+   else
+      echo -n $"$CONF not exist.";warning;echo
+      exit 1
+   fi
+fi
+
+PID_FILE=`grep "pidfile" ${CONF}|cut -d ' ' -f2`
+PID_FILE=${PID_FILE:=/var/run/redis.pid}
+LOCKFILE="/var/lock/subsys/redis-${REDIS_PORT}"
+
+if [ ! -x $REDIS ]; then
+    echo -n $"$REDIS not exist.";warning;echo
+    exit 0
+fi
+
+
+start() {
+
+    echo -n $"Starting $PROG: "
+    $REDIS $CONF
+    RETVAL=$?
+    if [ $RETVAL -eq 0 ]; then
+        success;echo;touch $LOCKFILE
     else
-      PID=$(cat $PIDFILE)
-      echo -n "Stopping $NAME: "
-      $CLIEXEC -s $SOCKET shutdown
-      echo "waiting for shutdown..."
-      while [ -x /proc/${PID} ]; do
-        sleep 0.1
-      done
-      echo "db stopped."
+        failure;echo
     fi
-    ;;
-  status)
-    if [ -f $PIDFILE ]; then
-      PID=$(cat $PIDFILE)
-      echo "running with pid: $PID"
+    return $RETVAL
+
+}
+
+stop() {
+
+    echo -n $"Stopping $PROG: "
+
+    if [ -f $PID_FILE ] ;then
+       read PID <  "$PID_FILE" 
+    else 
+       failure;echo;
+       echo -n $"$PID_FILE not found.";failure;echo
+       return 1;
+    fi
+
+    if checkpid $PID; then
+     kill -TERM $PID >/dev/null 2>&1
+        RETVAL=$?
+        if [ $RETVAL -eq 0 ] ;then
+                success;echo 
+                echo -n "Waiting for Redis to shutdown .."
+         while checkpid $PID;do
+                 echo -n "."
+                 sleep 1;
+                done
+                success;echo;rm -f $LOCKFILE
+        else 
+                failure;echo
+        fi
     else
-      echo "stopped."
-    fi
-    ;;
-  restart|force-reload)
-    $0 stop && $0 start
-    ;;
-  *)
-    echo "Argument \"$1\" not implemented."
-    exit 2
-    ;;
+        echo -n $"Redis is dead and $PID_FILE exists.";failure;echo
+        RETVAL=7
+    fi    
+    return $RETVAL
+
+}
+
+restart() {
+    stop
+    start
+}
+
+rhstatus() {
+    status -p ${PID_FILE} $PROG
+}
+
+hid_status() {
+    rhstatus >/dev/null 2>&1
+}
+
+case "$1" in
+    start)
+        hid_status && exit 0
+        start
+        ;;
+    stop)
+        rhstatus || exit 0
+        stop
+        ;;
+    restart)
+        restart
+        ;;
+    status)
+        rhstatus
+        RETVAL=$?
+        ;;
+    *)
+        echo $"Usage: $0 -p [port] {start|stop|status|restart}"
+        RETVAL=1
 esac
 
-exit 0
+exit $RETVAL
